

name: Upload to AWS S3

on:
  push:
    branches:
      - main

jobs:
  upload-aws-s3:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Upload AWS S3
      run: aws s3 mv Build/cifarm-build.data.unityweb s3://cifarm/cifarm-build.data.unityweb &
           aws s3 mv Build/cifarm-build.framework.js.unityweb s3://cifarm/cifarm-build.framework.js.unityweb &
           aws s3 mv Build/cifarm-build.loader.js s3://cifarm/cifarm-build.loader.js &
           aws s3 mv Build/cifarm-build.wasm.unityweb s3://cifarm/cifarm-build.wasm.unityweb & 
           wait
 
